groupId=rlp.footrix.pes6
artifactId=pes6es-player-extractor
version=1.0.0-SNAPSHOT
module.parameters=
generation.package=rlp.footrix.pes6.pes6esplayerextractor
dsl=[{"dsl":"sumus","dsl.version":"3.0.0","level":"Model","dsl.generation.package":"io.intino.sumus.model","builder":{"builder.groupId":"io.intino.magritte","builder.artifactId":"builder","builder.version":"7.0.6","builder.generation.package":"sumus"},"runtime":{"runtime.groupId":"io.intino.magritte","runtime.artifactId":"framework","runtime.version":"5.2.1"}}]
